# Generated by Django 5.0.2 on 2024-06-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='requisitos',
            field=models.CharField(blank=True, choices=[('No fumar', 'No fumar'), ('Mayores de 18', 'Mayores de 18'), ('No tener mascotas', 'No tener mascotas'), ('Certificado de estudios', 'Certificado de estudios'), ('Persona sola', 'Persona sola'), ('Solo mujeres', 'Solo mujeres'), ('Solo hombres', 'Solo hombres'), ('No hacer fiestas', 'No hacer fiestas'), ('No modificaciones a los enceres', 'No modificaciones a los enceres'), ('No hacer ruidos fuertes', 'No hacer ruidos fuertes')], max_length=200),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='servicios',
            field=models.CharField(choices=[('Internet', 'Internet'), ('Servicios públicos', 'Servicios públicos')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_bano',
            field=models.CharField(choices=[('Baño privado', 'Baño privado'), ('Baño compartido', 'Baño compartido')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Habitación', 'Habitación')], default='', max_length=20),
        ),
    ]
