# Generated by Django 5.0.2 on 2024-06-02 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_propiedad_requisitos_propiedad_servicios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='id_barrio',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='nombre_barrio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='id_propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='pagina.propiedad'),
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='requisitos',
        ),
        migrations.DeleteModel(
            name='Barrio',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='requisitos',
            field=models.ManyToManyField(blank=True, to='pagina.requisito'),
        ),
    ]
