# Generated by Django 5.0.2 on 2024-06-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_requisito_remove_propiedad_id_barrio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='requisitos',
            field=models.ManyToManyField(to='pagina.requisito'),
        ),
    ]
