# Generated by Django 5.0.2 on 2024-06-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_alter_propiedad_requisitos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='requisitos',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='requisitos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
