# Generated by Django 5.0.2 on 2024-06-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_remove_propiedad_requisitos_propiedad_requisitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='servicios',
            field=models.CharField(choices=[('Internet', 'Internet'), ('Servicios públicos', 'Servicios públicos')], default='', max_length=200),
        ),
    ]
